name: Weekly Report
on:
  schedule:
    - cron: "0 21 * * 0"
  workflow_dispatch:
jobs:
  report:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - name: Send Weekly Report
        env:
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
          MODE: "weekly"
        run: node alert.js
